services:
  psicowise.api:
    image: psicowise.api:latest
    container_name: psicowise.api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Joaquim12@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/aspnetapp.pfx
    volumes:
      - ./Psicowise/certs:/app/certs
    build:
      context: .
      dockerfile: Psicowise/Dockerfile
