services:
  psicowise.api:
    image: psicowise.api:latest
    container_name: psicowise.api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    build:
      context: .
      dockerfile: Psicowise/Dockerfile
