services:
  psicowise.api:
    image: psicowise.api:latest
    container_name: psicowise.api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8081
    build:
      context: .
      dockerfile: Psicowise/Dockerfile
