services:
  psicowise.api:
    image: psicowise.api:latest
    container_name: psicowise.api
    ports:
      - "49990:49990"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:49990
    volumes:
      - ./Psicowise/appsettings.json:/app/appsettings.json
    build:
      context: .
      dockerfile: Psicowise/Dockerfile
