services:
  psicowise.api:
    image: psicowise.api:latest
    container_name: psicowise.api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ./Psicowise/appsettings.json:/app/appsettings.json
    build:
      context: .
      dockerfile: Psicowise/Dockerfile
